name: teamtime
version: 9a
summary: A script to keep track of time for a globally distributed team.
description: |
 A script to keep track of time for globally distributed team.
grade: stable
confinement: strict
base: core20


apps:
  teamtime:
    command: bin/teamtime
    environment: 
       XAUTHORITY: $HOME/.Xauthority
    plugs:
      - home
      - network
      - network-bind
      - browser-support
      - desktop

parts:
  teamtime:
    plugin: python
    source: .
    stage-packages:
      - dbus-x11
