name: teamtime
version: 9a
summary: A script to keep track of time for a globally distributed team.
description: |
 A script to keep track of time for globally distributed team.
grade: stable
confinement: strict
base: core18


apps:
  teamtime:
    command: teamtime.py
    environment: 
       XAUTHORITY: $HOME/.Xauthority
    plugs:
      - home
      - network
      - network-bind
      - browser-support
      - desktop

parts:
  teamtime:
    plugin: python
    python-packages:
      - matplotlib
      - pandas
      - pandas-ext
      - geopy
      - plotly
      - pytz
      - prettytable
    stage-packages:
      - dbus-x11

  teamtime-script:
    plugin: dump
    source: .
