name: teamtime
version: 7b
summary: A script to keep track of time for a globally distributed team.
description: |
 A script to keep track of time for globally distributed team.
grade: stable
confinement: strict
base: core18


apps:
  teamtime:
    command: teamTime.py
    environment: 
       XAUTHORITY : $HOME/.Xauthority
    plugs:
    - home
    - network
    - network-bind
    - browser-support
    - desktop

parts:
  teamtime:
    plugin: python
    python-version: python3
    python-packages:
    - matplotlib
    - pandas
    - pandas-ext
    - geopy
    - plotly
    - pytz
    - prettytable

  wrapper:
    plugin: dump
    source: .

  mypackages:
    plugin: nil
    stage-packages:
    - python3
    - dbus-x11
